/* tslint:disable */
/* eslint-disable */
/**
 * Core web server
 * The core API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SendEventArgs
 */
export interface SendEventArgs {
    /**
     * 
     * @type {string}
     * @memberof SendEventArgs
     */
    'eventId': string;
}

