version: '3'

services:
  app:
    # Build the Docker image using the provided Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    # Map the host machine's port 3000 to the container's port 3000
    ports:
      - "3000:3000"
    # Optional: Define environment variables if needed
    environment:
      NODE_ENV: production
    # Optional: Mount volumes if needed (for example, for development purposes)
    volumes:
      - ./apps:/usr/src/app/apps
    depends_on:
      - redis
    networks:
      - app_network
  redis:
    image: "redis:latest"
    # Expose the default Redis port
    ports:
      - "6379:6379"
    networks:
      - app_network
networks:
  app_network:
    driver: bridge